### DISCUSSION TITLE
Accessing a Twig Component in a bundle

### DISCUSSION THREAD

**Discussion by tacman** [symfony/ux#2648] [Questions & Answers]
I'm not seeing the PHP Twig Component, only the templates.  So my call to the component that's in the bundle is failing.

```twig
<twig:SurvosFw:FwPage
        :caller="_self"
        :showBackButton="true"
>
  <twig:block name="content">
    This is in {{ _self }}, 
  </twig:block>

</twig:SurvosFw:FwPage>
```

I'm registering in the bundle config file

```php
        $builder->register(FwPage::class)->setAutowired(true)->setAutoconfigured(true)->setPublic(true);
```
 
And I can see the  templates.
```bash
bin/console debug:twig | grep Fw

  @SurvosFw              vendor/survos/fw-bundle/templates/                     
  @!SurvosFw             vendor/survos/fw-bundle/templates/                     
```

Does the component need a 'twig.component'  tag or something (I tried that, but it didn't work).

This works when I had the same code in the app, but not in the bundle.  Is there something special I need to do for twig namespaces to register them in the bundle?

**Comment by yceruto** [comment]
Could you show us the result of `php bin/console debug:twig-component`?

**Comment by yceruto** [comment]
Could you also show us the config for twig component? https://symfony.com/bundles/ux-twig-component/current/index.html#configuration
```yaml
# config/packages/twig_component.yaml
twig_component:
    defaults:
        # short form: components under this namespace:
        #    - name will be the class name that comes after the prefix
        #        App\Twig\Components\Alert => Alert
        #        App\Twig\Components\Button\Primary => Button:Primary
        #    - templates will live in "components/"
        #        Alert => templates/components/Alert.html.twig
        #        Button:Primary => templates/components/Button/Primary.html.twig
        App\Twig\Components\: components/
```
You might need to prepend you namespace and components/ template path for your bundle if it's not already the case

**Reply by tacman** [reply]
```
php bin/console config:dump twig_component
# Default configuration for extension with alias: "twig_component"
twig_component:
    defaults:

        # Prototype
        namespace:
            template_directory:   components
            name_prefix:          ''

    # Defaults to `components`
    anonymous_template_directory: ~

    # Enables the profiler for Twig Component (in debug mode)
    profiler:             '%kernel.debug%'
    controllers_json:     null
```

```yaml
twig_component:
    anonymous_template_directory: 'components/'
    defaults:
        # Namespace & directory for components
        App\Twig\Components\: 'components/'
```
