### ISSUE TITLE
BatchActionController isn't passing default route attributes

### ISSUE THREAD

**Issue by quisse** [symfony/ux#1022]
Let's say we register the `ux_live_component` routes as following:
```
live_component:
    resource: '@LiveComponentBundle/config/routes.php'
    prefix: '/_components'
    defaults:
       _routeScope: ['storefront']
       _loginRequired: true 
```
When the `\Symfony\UX\LiveComponent\Controller\BatchActionController::__invoke` is invoking sub requests, it sets the only certain attributes. So that for example the `_loginRequired` and `_routeScope` defaults are skipped. I want to create a PR to address this issue but not sure where to look. As the defaults are added to the routes at compile time and the batchAction is invoking the requests directly so that the route matching (and default attributes logic) is skipped.
