### ISSUE TITLE
[TwigComponent] set anonymous template in a bundle directory 

### ISSUE THREAD

**Issue by alinceDev** [symfony/ux#1360]
Hi,

I can't set the anonymous_template_directory setting to a path located in a bundle in the vendor directory.

I tried like this : 
```yaml
   anonymous_template_directory: '%kernel.project_dir%/vendor/...../'
   # or
   anonymous_template_directory: '@CoreBundle/components/'
```

I want to create some anonymous components that I want to share between multiple projects.

Thanks

**Comment by smnandre** [comment]
As of today, it's not possible to set the anonymous template directory outside your app.


I think your second syntax may be the easiest one to implement.

We would probably then need to declare a PSR-4-like "namespace" map, to keep the 1 <-> 1 relation between templates and component names.

Something like:

```yaml
   anonymous_template_namespaces: 
       Foo: '@CoreBundle/components'
       # (or maybe the contrary, but that's a minor debate)
       # '@CoreBundle/components': Foo
```

```twig
{# Would use the anonymous component template located in '@CoreBundle/components/Button.html.twig' #}
<twig:Foo:Button />
```

What do you think ?

**Comment by alinceDev** [comment]
Does this implementation will work with sub folder in the components folder ?
- '@CoreBundle/components/Button/Primary.html.twig'
- '@CoreBundle/components/Form/Select.html.twig'    
- '@CoreBundle/components/Form/Checkbox.html.twig'    

If it's complex to implement, can we have something like this ?

```yml
   anonymous_template_namespaces: 
       Button: '@CoreBundle/components/Button,
       Form: '@CoreBundle/components/Form,
```

<twig:Button:Primary />
<twig:Form:Select />
<twig:Form:Checkbox />

**Comment by smnandre** [comment]
Just beeing curious… We only speak about anonymous components there, right ? Do you use props or blocks inside them ? Or is this mainly « includes » (with better syntax) ? 

(I’ thinking a lot of « static components » those days)


For the namespaces i hope i’ll have some time this week to try something :)

**Comment by smnandre** [comment]
Well i think.... that it already works 😄 

(with a minor constraint (having a "components" folder in your Bundle templates)

--

I was sure i already worked on this question and thank to you i finally remembered :)  🍸 

We do not handle multiple directories..... because Twig already does it ! 

## How to solve your need

Let's go back to the initial configuration of TwigComponent:

```
# config/packages/twig_component.yaml
twig_component:
    anonymous_template_directory: 'components/'
    # ...
```

The only thing we say here is that "Form:Button" will be mapped to "components/Form/Button.html.twig" ... 
... but we don't say _where_ is the components directory.

So if you add a directory in the Twig configuration...

```
# config/packages/twig.yaml
twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        'vendor/your-company/core-bundle/templates': ~
```

... when Twig will look for `components/Form/Button.html.twig`, it will first look in your bundle (in `core-bundle/templates/components/Form/Button.html.twig`) and fallback on the local path if the template does not exists in CoreBundle.

## Some comments

Note: you can use an absolute path instead of '`vendor/....`' but, the syntax '`@CoreBundle`' will not work herer.

⚠️  Two minor warnings
* The debug:twig-component will have illogical results, and that is "normal"
* You will probably need to manually refresh your cache if you edit your components

⚠️ ⚠️  A real warning
ANY view will be looked in your Bundle first, **then** your app directory
This would have no performance impact in production as everything will be cached
But keep it in mind if you don't understand why a local template is ignored :)
