### ISSUE TITLE
Chart.js doesn't show when AssetMapper is used.

### ISSUE THREAD

**Issue by oleksiivelychko** [symfony/ux#1449]
Before I had Chart.js implementation and it worked with Webpack Encore bundle. Recently I've switched to AssetMapper. I did all steps from Chart.js [official documentation](https://symfony.com/bundles/ux-chartjs/current/index.html)
As I see there are two ways to add Chart.js, and in case when I use AssetMapper I don't have to have any NPM packages anymore. AssetMapper has to resolve all JS dependencies. 

But, I got empty block on the page:
<img width="1184" alt="image" src="https://github.com/symfony/ux/assets/94033630/eeecb043-0446-4e4b-bc38-3ed3be105438">

My current configuration:

**assets/bootstrap.js**
```
import { startStimulusApp } from '@symfony/stimulus-bundle';
const app = startStimulusApp();
```
**assets/controllers.json**
```
{
    "controllers": {
        "@symfony/ux-chartjs": {
            "chart": {
                "enabled": true,
                "fetch": "lazy"
            }
        }
    },
    "entrypoints": []
}
```
**importmap.php**
```
<?php
return [
    'app' => [
        'path' => './assets/app.js',
        'entrypoint' => true,
    ],
    'auth' => [
        'path' => './assets/auth.js',
        'entrypoint' => true,
    ],
    '@symfony/stimulus-bundle' => [
        'path' => './vendor/symfony/stimulus-bundle/assets/dist/loader.js',
    ],
    '@hotwired/stimulus' => [
        'version' => '3.2.2',
    ],
    'chart.js/auto' => [
        'version' => '3.9.1',
    ],
    '@kurkle/color' => [
        'version' => '0.3.2',
    ],
    'bootstrap' => [
        'version' => '5.3.2',
    ],
    '@popperjs/core' => [
        'version' => '2.11.8',
    ],
    'bootstrap/dist/css/bootstrap.min.css' => [
        'version' => '5.3.2',
        'type' => 'css',
    ],
];
```
**config/packages/stimulus.yaml**
```
stimulus:
  controller_paths:
    - '%kernel.project_dir%/assets/controllers'
  controllers_json: '%kernel.project_dir%/assets/controllers.json'
```
**config/packages/asset_mapper.yaml**
```
framework:
    asset_mapper:
        # The paths to make available to the asset mapper.
        paths:
            - assets/
```

I compile assets via `asset-map:compile` command.
I removed **symfony/webpack-encore-bundle** package from **composer.json** and I have **symfony/ux-chartjs** and **symfony/stimulus-bundle** packages only. Both have **^2.14.0** version.

So, is it possible to use Chart.js (or any other UX component) with AssetMapper only and without WebPack bundle at all?
