### ISSUE TITLE
[LiveComponent] Test helper doesn't work with localized components

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/ux#1565]
If your live components are localized as explained in https://symfony.com/bundles/ux-live-component/current/index.html#installation:

```yaml
# config/routes/ux_live_component.yaml
live_component:
    resource: '@LiveComponentBundle/config/routes.php'
    prefix: /{_locale}/_components
```

You can't use the test helper (https://symfony.com/bundles/ux-live-component/current/index.html#test-helper) because you'll see this error:

```
Symfony\Component\Routing\Exception\MissingMandatoryParametersException:
Some mandatory parameters are missing ("_locale") to generate a URL for route "ux_live_component".
```

The arguments used to generate the URL seem hardcoded, so I don't know how to solve this:

https://github.com/symfony/ux/blob/1a4f208c890ce2a9348e031674b4fb9df8199bc1/src/LiveComponent/src/Test/TestLiveComponent.php#L132-L138

Thanks!
