### ISSUE TITLE
[TwigComponents] Classes not found(Pimcore)

### ISSUE THREAD

**Issue by plixus** [symfony/ux#1895]
Hi, I have installed Symfony UX Components and Flex has created the twig_component.yaml for me as described in the documentation. I created a few components with the Maker Bundle and it created all Template and PHP class files correctly.
Using Components in template is rendering them correctly.

But running debug:twig-component I see that all my Components are of type "Anon" as the class is not found.

**Can anyone help me, what am I missing?**

```
+---------------------------+-------+--- Components ---------------------------------+------+
| Name                      | Class | Template                                       | Type |
+---------------------------+-------+------------------------------------------------+------+
| Button                    |       | components/Button.html.twig                    | Anon |
| PrintContentElement       |       | components/PrintContentElement.html.twig       | Anon |
| Alert                     |       | components/Alert.html.twig                     | Anon |
| PrintContentElementLayout |       | components/PrintContentElementLayout.html.twig | Anon |

```
config/packages/twig_component.yaml:
```
twig_component:
    anonymous_template_directory: 'components/'
    defaults:
        # Namespace & directory for components
        App\Twig\Components\: 'components/'
```

src/Twig/Components/Button.php:
```
<?php

namespace App\Twig\Components;

use Symfony\UX\TwigComponent\Attribute\AsTwigComponent;

#[AsTwigComponent]
final class Button
{
}

```
templates/components/Button.html.twig
```
<div{{ attributes.defaults({class: 'button'}) }}>
    {% block content %}{% endblock %}
</div>
```
