### ISSUE TITLE
[Turbo] Web Debug Toolbar script is blocked by CSP when navigating

### ISSUE THREAD

**Issue by DavidPetrasek** [symfony/ux#2134]
On initial page load the toolbar works fine, but is missing after visiting a link via Turbo Drive.

This is the console output from Google Chrome:
```
turbo.es2017-esm.js:4651 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src https://127.0.0.1:5173 'nonce-ZkGUwME8QO5iHCXt1kgvHw==' 'unsafe-inline' 'nonce-e276b18f073898209eb899b46ffa3f01'". Note that 'unsafe-inline' is ignored if either a hash or nonce value is present in the source list.

renderElement @ turbo.es2017-esm.js:4651
assignNewBody @ turbo.es2017-esm.js:4826
(anonymní) @ turbo.es2017-esm.js:4732
preservingPermanentElements @ turbo.es2017-esm.js:1717
preservingPermanentElements @ turbo.es2017-esm.js:1814
replaceBody @ turbo.es2017-esm.js:4730
render @ turbo.es2017-esm.js:4682
renderSnapshot @ turbo.es2017-esm.js:1523
render @ turbo.es2017-esm.js:1483
```

The CSP is handled by the NelmioSecurityBundle. Here is an excerpt from its config file (nelmio_security.yaml):
```
...
csp:
        hosts: []
        content_types: []
        enforce:
            level1_fallback: false
            browser_adaptive:
                enabled: false
            # report-uri: '%router.request_context.base_url%/nelmio/csp/report'
            default-src:
                - 'none'
            style-src:
                - 'self'
                - https://www.gstatic.com https://fonts.googleapis.com                                # Google Fonts
            font-src:
                - 'self'
                - https://fonts.googleapis.com https://fonts.gstatic.com                              # Google Fonts
            img-src:
                - 'self' 
                - 'data:'
                - https://tile.openstreetmap.org/
            form-action:
                - 'self'
            frame-src:
                - 'self'
                - 'blob:'
                - https://www.google.com
            frame-ancestors:
                - 'self'
            object-src:
                - 'self'
            media-src:
                - 'self'
            connect-src:
                - 'self' 
                - 'wss:'
                - https://tile.openstreetmap.org/
            block-all-mixed-content: true # defaults to false, blocks HTTP content over HTTPS transport
            # upgrade-insecure-requests: true # defaults to false, upgrades HTTP requests to HTTPS transport
...
```
