### ISSUE TITLE
Turbo & Mercure documentation does not work

### ISSUE THREAD

**Issue by hafkenscheid** [symfony/ux#2518]
The Turbo / Mercure documentation is inconsistent: 

The following (can be found https://github.com/symfony/ux/blob/2.x/src/Turbo/doc/index.rst?plain=1#L519-L522) does generate an error:
```yaml
# config/packages/turbo.yaml
turbo:
    mercure:
        hubs: [default]
```

> Unrecognized option "mercure" under "turbo". Available options are "broadcast", "default_transport".

I don't get how this can work, as there is no code referring to this option in the configuration: https://github.com/symfony/ux/blob/2.x/src/Turbo/src/DependencyInjection/Configuration.php
