### ISSUE TITLE
aliases should not have the same validations as icon names

### ISSUE THREAD

**Issue by tacman** [symfony/ux#2721]
I would like to alias my icons by class name:

```yaml
# config/packages/ux_icons.yaml
ux_icons:
  aliases:
     'App\\Entity\\Article': tabler:news
     edit: tabler:edit
```

That way, I can display an entity icon easily.

```twig
            {{ ux_icon(article|get_class) }}
```

But I get

> An exception has been thrown during the rendering of a template ("The icon name "App\Entity\Article" is not valid.") in [app/index.html.twig at line 22](file://app/index.html.twig#L22).

I think the validation should happen after the aliases have been checked.

**Comment by tacman** [comment]
Oops!  Already works, too many slashes.  Should be

```yaml
# config/packages/ux_icons.yaml
ux_icons:
  aliases:
     'App\Entity\Article': tabler:news
     edit: tabler:edit
```
