### ISSUE TITLE
[Turbo] TurboStreamListenRenderer service doesn't register correctly when Mercure Hub is mocked

### ISSUE THREAD

**Issue by milankaranovic** [symfony/ux#2775]
Hey everyone! 👋🏻 

I updated `symfony/ux-turbo` from `v2.23.0` to `2.25.2` and my tests (WebTestCase) started failing with this error
```
ErrorException: An exception has been thrown during the rendering of a template 
("Too few arguments to function Symfony\UX\Turbo\Bridge\Mercure\TurboStreamListenRenderer::__construct(), 
3 passed in /app/var/cache/test/ContainerO3ffV3d/getTurbo_Mercure_Default_RendererService.php
 on line 31 and exactly 4 expected") in "foo.html.twig" at line 31.
```
On line 31 is `turbo_stream_listen`. 

Additionally, I have`mercure.hub.default` mocked according to these instructions https://symfony.com/doc/current/mercure.html#testing

I see that this PR https://github.com/symfony/ux/pull/2447 has been merged in `v2.24.0`, and a lot of things related to `turbo_stream_listen` has changed, including `RegisterMercureHubsPass`. It loops through `mercure.hub` tags, so I ended up with this solution

```yaml
# config/services_test.yaml
services:
    mercure.hub.default:
        class: Tests\Services\MockMercureHub
        tags:
            - 'mercure.hub'
```

Reporting this because I'm not sure if this is a bug or if the documentation has to be updated.

**Comment by Kocal** [comment]
Hi,

I tried to reproduce your issue but without success. 

If I create a Hub stub like this:
```php
<?php

declare(strict_types=1);

namespace App\Mercure;

use Symfony\Component\Mercure\HubInterface;
use Symfony\Component\Mercure\Jwt\TokenFactoryInterface;
use Symfony\Component\Mercure\Jwt\TokenProviderInterface;
use Symfony\Component\Mercure\Update;

final readonly class HubStub implements HubInterface
{
    public function __construct(
        private string $publicUrl,
    ) {
    }

    public function getUrl(): string
    {
        // TODO: Implement getUrl() method.
    }

    public function getPublicUrl(): string
    {
        return $this->publicUrl;
    }

    public function getProvider(): TokenProviderInterface
    {
        // TODO: Implement getProvider() method.
    }

    public function getFactory(): ?TokenFactoryInterface
    {
        // TODO: Implement getFactory() method.
    }

    public function publish(Update $update): string
    {
        return 'id';
    }
}
```

and register-it in my configuration like this:
```yaml
# config/services_test.yaml
services:
    mercure.hub.default:
        class: App\Mercure\HubStub
        arguments:
            - '%env(MERCURE_PUBLIC_URL)%'
```

Running a PHPUnit `KernelTestCase` with `dump(self::getContainer()->get(HubInterface::class))` correctly shows me my `App\Mercure\HubStub` instance. 

Maybe do you have a reproducer?
