### ISSUE TITLE
Fixed dependence between Composer & NPM/Yarn

### ISSUE THREAD

**Issue by alexander-bogomolov** [symfony/ux#47]
The hard linking to the files form "vendor" into the package.json provides a hard dependency between PHP and JS package managers.

Currently, most of our projects deploy through the Bitbucket Pipeline. For this, two different images are used one after the other:
- node - This is where the assets are built and stored as artifacts. (`yarn install && yarn run build`)
- php - Here the project is rolled out with Deployer and the assets are taken along. (`php bin/deployer.phar deploy development`)

### Example
```YAML
buildAssetsForDevelopment: &buildAssetsForDevelopment
  step:
    name: "Build assets"
    image: node:12.18.3
    caches:
      - node
    script:
      - yarn install
      - yarn run dev
    artifacts:
      - public/build/**

deployToDevelopment: &deployToDevelopment
  step:
    name: "Deploy to development"
    deployment: deployment-development
    image: php:7.4
    script:
      - apt-get update -y && apt-get install -y ssh rsync
      - php bin/deployer.phar deploy development --branch=$BITBUCKET_BRANCH -vvv

pipelines:
  custom:
    deployment-to-dev:
      - <<: *buildAssetsForDevelopment
      - <<: *deployToDevelopment
```

Now if you want to use UX, you are forced to rely on a more complex image that includes both Node and PHP.

Is it intended to outsource the dependency in symfony/ux-* into a separate symfony/ux-* NPM package?
