### ISSUE TITLE
[Turbo] allow adding an "interceptor controller" to the route which gets invoked when the request is a Turbo Stream compatible request

### ISSUE THREAD

**Issue by dkarlovi** [symfony/ux#518]
When you want to add streams to an existing app, my idea is to

1. register a new controller which listens to the same route as the original, but expects the correct `Accept` header
2. it forwards the request to the original controller, without the `Accept` header
3. it then allows rendering a separate response either based on 2. response or something else entirely

See a functional example here, I'm using a tag (with a `route` property) to link the controller to a route, but it could be an attribute or similar. It would be a nice addition since the mechanics of this are not totally trivial to get right, because of the stripping of the header, subrequests, etc.
https://github.com/symfony/ux/issues/518#issuecomment-1297295599

**Comment by dkarlovi** [comment]
This concept seems to be somewhat harder to understand from comments in Symfony Slack so I'll try to outline it a bit better here:
1. you have an existing route, say
```yaml
add_to_cart:
    path: /cart/add
    method: POST
    controller: Some3rdPartyCartController
```
2. this route works like `POST /cart/add, product=123`
3. we add a new route
```yaml
streams_add_to_cart:
    path: /cart/add
    method: POST
    controller: CustomStreamsSpecificCartController
    conditions: request.accept == 'text/vnd.turbo-stream.html'
```
4. this route works like `POST /cart/add, product=123, Accept: text/vnd.turbo-stream.html`
5. the `CustomStreamsSpecificCartController` does something like
```php
__invoke()
{
    // invoke the original request, but without the Accept: text/vnd.turbo-stream.html
    
    return $this->render('add_to_cart.stream.html.twig', $anyCustomDataStreamsTemplateRequires);
}
```
6. we should be able to do this automatically as much as possible, ideally without needing to copy/paste routes manually, for example an annotation like
```php
#[StreamRoute("add_to_cart")]
```
would be enough.

# Why not do it in the original controller?

The original controller should work exactly as before, it's untouched.

# Why not in a request listener?

We don't know which stream controller to point to, we need a place to put the controller name for each route we want to stream, which is exactly what "a route" is.

# Why do you need a separate controller for each route?

Each route's Twig template could require separate, context specific information, the controller is used to differentiate this.

/cc @weaverryan I know you've been doing something similar in Casts.
