### ISSUE TITLE
[UX-TURBO] turbo_stream_listen returns 401 in production

### ISSUE THREAD

**Issue by YummYume** [symfony/ux#716]
Hello. Thanks for making Symfony UX, it's incredible.

I currently run into a problem while using Turbo with Mercure and I'm not too sure if I should report it here or in the Mercure repo so I'm trying my luck here.

My Mercure hub is currently proxied by Nginx and works perfectly in dev. I have a voting system and when someone votes, the vote count updates thanks to the `#[Broadcast]` attribute and the `turbo_stream_listen` twig method.
In prod, however, I seem always to get a 401 Unauthorized response from Mercure no matter what. The votes are not even private, everyone should be able to see them.

**Mercure service**
```yaml
mercure:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      SERVER_NAME: ":3000"
      MERCURE_PUBLISHER_JWT_KEY: "${MERCURE_JWT_SECRET:?err}"
      MERCURE_SUBSCRIBER_JWT_KEY: "${MERCURE_JWT_SECRET:?err}"
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins http://localhost
        use_forwarded_headers "1"
    # Uncomment the following line to enable the development mode
    command: /usr/bin/caddy run --config /etc/caddy/Caddyfile.dev
    container_name: su-mercure
    volumes:
      - ./data/mercure/data:/data
      - ./data/mercure/config:/config
```

This config is the same in production, except for the `command` part which is removed.

**Nginx proxy**
```nginx
server {
    listen 3000;
    server_name localhost;

    location /.well-known/mercure {
        proxy_pass http://mercure:3000;
        proxy_read_timeout 24h;
        proxy_http_version 1.1;
        proxy_set_header Connection "";

        ## Be sure to set USE_FORWARDED_HEADERS=1 to allow the hub to use those headers ##
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```

The only difference is that in production, the proxy uses https and listens to hub.my-domain instead of port 3000. But other than that it's the same.

If that helps, the site is live and the 401 response can be observed from there : https://stack-up.tech/en/tech/tailwind. When I check the logs, it just gives me a generic "Subscriber unauthorized" : 

```
su-mercure  | {"level":"info","ts":1677854488.8285167,"logger":"http.handlers.mercure","msg":"Subscriber unauthorized","subscriber":{"id":"redacted","last_event_id":"","remote_addr":"redacted"}}
su-mercure  | 2023/03/03 14:41:28.828   ERROR   http.log.access.log0    handled request {"request": {"remote_ip": "redacted", "remote_port": "58346", "proto": "HTTP/1.1", "method": "GET", "host": "mercure:3000", "uri": "/.well-known/mercure?topic=https%3A%2F%2Fsymfony.com%2Fux-turbo%2FApp%255CEntity%255CVote%2F%7Bid%7D", "headers": {"Referer": ["https://stack-up.tech/"], "Accept-Encoding": ["gzip, deflate, br"], "X-Forwarded-Host": ["hub.stack-up.tech"], "X-Forwarded-Proto": ["https"], "Accept": ["text/event-stream"], "Sec-Ch-Ua-Mobile": ["?0"], "Sec-Fetch-Mode": ["cors"], "Sec-Fetch-Dest": ["empty"], "X-Forwarded-For": ["redacted"], "Sec-Ch-Ua": ["\"Chromium\";v=\"110\", \"Not A(Brand\";v=\"24\", \"Google Chrome\";v=\"110\""], "Cache-Control": ["no-cache"], "User-Agent": ["Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36"], "Sec-Ch-Ua-Platform": ["\"Linux\""], "Origin": ["https://stack-up.tech"], "Sec-Fetch-Site": ["same-site"], "Pragma": ["no-cache"]}}, "user_id": "", "duration": 0.000111678, "size": 13, "status": 401, "resp_headers": {"Access-Control-Allow-Origin": ["https://stack-up.tech"], "Content-Type": ["text/plain; charset=utf-8"], "Server": ["Caddy"], "Content-Security-Policy": ["default-src 'self'"], "X-Frame-Options": ["DENY"], "X-Content-Type-Options": ["nosniff"], "X-Xss-Protection": ["1; mode=block"], "Access-Control-Allow-Credentials": ["true"]}}
```
