### ISSUE TITLE
[TwigComponent] Release 2.8.0 breaks (my) cache:clear command run

### ISSUE THREAD

**Issue by manuelkiessling** [symfony/ux#881]
When upgrading `symfony/ux-twig-component` from `2.7.1` to `2.8.0` (or 2.8.1 for that matter) on a Symfony 6.2 codebase, the `composer` run (as well as subsequent `bin/console cache:clear` runs) is stuck at `Executing script cache:clear` (vs only taking 1-2 seconds before the upgrade).

I've isolated TwigComponent as the culprit by updating only this dependency via `composer require "symfony/ux-twig-component@2.8.0"`.

It finally bails out due to the 300 seconds timeout.

However, I fear that the issue is specific to my setup, because setting up a new project via `symfony new ux_bug_test --version="6.2.*" --webapp` and running `composer require "symfony/ux-twig-component@2.8.0"` doesn't yield the issue.

**Comment by manuelkiessling** [comment]
Ok, got a bit closer to the root cause. My `twig.yaml` looks like this:

```yaml
twig:
    default_path: '%kernel.project_dir%/templates'

    paths:
        '%kernel.project_dir%/public/generated-content/': 'generated_content'
```

When removing the `'%kernel.project_dir%/public/generated-content/': 'generated_content'` line OR when removing all files in `%kernel.project_dir%/public/generated-content`, the issue disappears.
